sudo: required
services:
  - docker
language: node_js
node_js:
  - '8'
before_install:
  - yarn global add greenkeeper-lockfile@1
  - greenkeeper-lockfile-update
install:
  - yarn --frozen-lockfile
  - mv .env.test .env
script:
  - yarn run test
after_success:
  - greenkeeper-lockfile-upload
  - bash <(curl -s https://codecov.io/bash)
  - |
    # if we're on a master non-PR, deploy as latest
    if [[ ( $TRAVIS_BRANCH == "master" ) && ( $TRAVIS_PULL_REQUEST == "false" ) ]]; then
      ./scripts/deploy-master.sh || exit 1
    # if we're a tag, build to hub only
    elif [ -n "${TRAVIS_TAG}" ]; then
      ./scripts/deploy-tag.sh || exit 1
    fi
notifications:
  email: false
cache:
  yarn: true
