
sudo: required
services:
  - docker
language: node_js
node_js:
  - "8.11"
install:
  - yarn --frozen-lockfile
  - mv .env.test .env
script:
  - true
after_success:
  - |
    if [[ $TRAVIS_BRANCH == "master" ]]; then
      heroku container:login &&
      heroku container:push -a prowl-github-app web &&
      heroku container:release -a prowl-github-app web ||
      exit 1
    fi
notifications:
  email: false
cache:
  yarn: true
