
sudo: required
services:
  - docker
language: node_js
node_js:
  - "8.11"
install:
  - yarn --frozen-lockfile
  - mv .env.test .env
script:
  - true
after_success:
  - |
    if [[ $TRAVIS_BRANCH == "master" ]]; then
      ./deploy.sh || exit 1
    fi
notifications:
  email: false
cache:
  yarn: true
