
sudo: required
services:
  - docker
language: node_js
node_js:
  - "8.11"
install:
  - yarn --frozen-lockfile
  - mv .env.test .env
script:
  - yarn run test
after_success:
  - |
    if [[ ( $TRAVIS_BRANCH == "master" ) && ( $TRAVIS_PULL_REQUEST == "false" ) ]]; then
      ./scripts/deploy-master.sh || exit 1
    elif [ -z "${TRAVIS_TAG}" ]; then
      ./scripts/deploy-tag.sh || exit 1
    fi
notifications:
  email: false
cache:
  yarn: true

